In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('trade-data.csv',encoding='latin1')

In [5]:
df.head()
print(df.shape)
df.head(7072)

(7072, 7)

,Indicator,Reporting Economy,Partner Economy,Period,Unit,Year,Value
0,Total merchandise imports - monthly,China,World,January,Million US dollar,2018,181151.0000
1,Total merchandise imports - monthly,China,World,January,Million US dollar,2019,179664.2075
2,Total merchandise imports - monthly,China,World,February,Million US dollar,2019,132368.2261
3,Total merchandise imports - monthly,China,World,February,Million US dollar,2020,299544.2047
4,Total merchandise imports - monthly,China,World,February,Million US dollar,2018,138345.0000
5,Total merchandise imports - monthly,China,World,March,Million US dollar,2018,179694.0000
6,Total merchandise imports - monthly,China,World,March,Million US dollar,2020,164775.4201
7,Total merchandise imports - monthly,China,World,March,Million US dollar,2019,166862.6642
8,Total merchandise imports - monthly,China,World,April,Million US dollar,2019,180527.8156
9,Total merchandise imports - monthly,China,World,April,Million US dollar,2020,154610.7658
10,Total merchandise imports - monthly,China,World,April,Million US dollar,2018,172719.0000
11,Total merchandise imports - monthly,China,World,May,Million US dollar,2018,188177.0000
12,Total merchandise imports - monthly,China,World,May,Million US dollar,2020,143877.0681
13,Total merchandise imports - monthly,China,World,May,Million US dollar,2019,172771.0925
14,Total merchandise imports - monthly,China,World,June,Million US dollar,2020,166630.0211
15,Total merchandise imports - monthly,China,World,June,Million US dollar,2018,174691.0000
16,Total merchandise imports - monthly,China,World,June,Million US dollar,2019,162813.4506
17,Total merchandise imports - monthly,China,World,July,Million US dollar,2019,177757.8632
18,Total merchandise imports - monthly,China,World,July,Million US dollar,2018,186914.0000
19,Total merchandise imports - monthly,China,World,July,Million US dollar,2020,174981.1883
20,Total merchandise imports - monthly,China,World,August,Million US dollar,2020,175946.0490
21,Total merchandise imports - monthly,China,World,August,Million US dollar,2018,190652.0000
22,Total merchandise imports - monthly,China,World,August,Million US dollar,2019,180157.1526
23,Total merchandise imports - monthly,China,World,September,Million US dollar,2019,179136.4856
24,Total merchandise imports - monthly,China,World,September,Million US dollar,2018,195134.0000
25,Total merchandise imports - monthly,China,World,September,Million US dollar,2020,201968.5534
26,Total merchandise imports - monthly,China,World,October,Million US dollar,2020,178171.1951
27,Total merchandise imports - monthly,China,World,October,Million US dollar,2018,181786.0000
28,Total merchandise imports - monthly,China,World,October,Million US dollar,2019,170670.6110
29,Total merchandise imports - monthly,China,World,November,Million US dollar,2019,184266.4531
...,...,...,...,...,...,...,...
7042,Commercial services exports of selected econom...,United States of America,World,March,% change over the same period of the previous ...,2019,0.0000
7043,Commercial services exports of selected econom...,United States of America,World,March,% change over the same period of the previous ...,2018,7.0000
7044,Commercial services exports of selected econom...,United States of America,World,March,% change over the same period of the previous ...,2020,-19.0000
7045,Commercial services exports of selected econom...,United States of America,World,April,% change over the same period of the previous ...,2018,3.0000
7046,Commercial services exports of selected econom...,United States of America,World,April,% change over the same period of the previous ...,2019,3.0000
7047,Commercial services exports of selected econom...,United States of America,World,April,% change over the same period of the previous ...,2020,-27.0000
7048,Commercial services exports of selected econom...,United States of America,World,May,% change over the same period of the previous ...,2020,-27.0000
7049,Commercial services exports of selected econom...,United States of America,World,May,% change over the same period of the previous ...,2018,3.0000
7050,Commercial services exports of selected econom...,United States of America,World,May,% change over the same period of the previous ...,2019,4.0000
7051,Commercial services exports of selected econom...,United States of America,World,June,% change over the same period of the previous ...,2019,4.0000
7052,Commercial services exports of selected econom...,United States of America,World,June,% change over the same period of the previous ...,2018,3.0000
7053,Commercial services exports of selected econom...,United States of America,World,June,% change over the same period of the previous ...,2020,-27.0000
7054,Commercial services exports of selected econom...,United States of America,World,July,% change over the same period of the previous ...,2020,-26.0000
7055,Commercial services exports of selected econom...,United States of America,World,July,% change over the same period of the previous ...,2018,3.0000
7056,Commercial services exports of selected econom...,United States of America,World,July,% change over the same period of the previous ...,2019,2.0000
7057,Commercial services exports of selected econom...,United States of America,World,August,% change over the same period of the previous ...,2019,2.0000
7058,Commercial services exports of selected econom...,United States of America,World,August,% change over the same period of the previous ...,2018,3.0000
7059,Commercial services exports of selected econom...,United States of America,World,August,% change over the same period of the previous ...,2020,-26.0000
7060,Commercial services exports of selected econom...,United States of America,World,September,% change over the same period of the previous ...,2020,-25.0000
7061,Commercial services exports of selected econom...,United States of America,World,September,% change over the same period of the previous ...,2018,3.0000
7062,Commercial services exports of selected econom...,United States of America,World,September,% change over the same period of the previous ...,2019,1.0000
7063,Commercial services exports of selected econom...,United States of America,World,October,% change over the same period of the previous ...,2019,2.0000
7064,Commercial services exports of selected econom...,United States of America,World,October,% change over the same period of the previous ...,2018,2.0000
7065,Commercial services exports of selected econom...,United States of America,World,October,% change over the same period of the previous ...,2020,-25.0000
7066,Commercial services exports of selected econom...,United States of America,World,November,% change over the same period of the previous ...,2020,-24.0000
7067,Commercial services exports of selected econom...,United States of America,World,November,% change over the same period of the previous ...,2018,1.0000
7068,Commercial services exports of selected econom...,United States of America,World,November,% change over the same period of the previous ...,2019,2.0000
7069,Commercial services exports of selected econom...,United States of America,World,December,% change over the same period of the previous ...,2019,2.0000
7070,Commercial services exports of selected econom...,United States of America,World,December,% change over the same period of the previous ...,2018,1.0000
7071,Commercial services exports of selected econom...,United States of America,World,December,% change over the same period of the previous ...,2020,-24.0000

In [11]:
df['Value']

0       181151.0000
1       179664.2075
2       132368.2261
3       299544.2047
4       138345.0000
           ...
7067         1.0000
7068         2.0000
7069         2.0000
7070         1.0000
7071       -24.0000
Name: Value, Length: 7072, dtype: float64

In [6]:
indicators = ['Total merchandise imports - monthly','Total merchandise exports - monthly','Commercial services exports of selected economies monthly','Commercial services imports of selected economies monthly']

In [7]:
for i in indicators:
    print(i)

Total merchandise imports - monthly
Total merchandise exports - monthly
Commercial services exports of selected economies monthly
Commercial services imports of selected economies monthly

In [16]:
t = df['Reporting Economy'].unique().tolist()
print(t)

['China', 'India', 'Italy', 'Spain', 'United States of America']